### ISSUE TITLE
Implementation without FINE_LOCATION

### ISSUE THREAD

**Issue by ssomnoremac** [syarul/react-native-android-location#3]
Wondering if there's a way to implement this plugin so that `FINE_LOCATION` is not a requirement and gps is not used at all? I

**Comment by syarul** [comment]
You can modify the [RNALocationModule](https://github.com/syarul/react-native-android-location/blob/master/src/main/java/com/syarul/rnalocation/RNALocationModule.java) by implementing your own method of `Location Manager`. Then you can turn off `FINE_LOCATION` if that not being use.
